import { addDays, todayInput } from './date';
import type {
  ActivityLog,
  ClientProjectAccess,
  NotificationItem,
  Profile,
  Project,
  ProjectNote,
  RevisionActivity,
  RevisionAttachment,
  RevisionItem,
  RevisionNote,
  RevisionRequest,
} from './types';

const now = new Date().toISOString();

export const sampleProfiles: Profile[] = [
  {
    id: 'tahir-admin',
    full_name: 'Tahir',
    email: 'tahir@manuscriptheaven.com',
    role: 'admin',
    phone: '+1 555 0101',
    status: 'active',
    avatar_url: null,
    created_at: now,
  },
  {
    id: 'atia-manager',
    full_name: 'Atia',
    email: 'atia@manuscriptheaven.com',
    role: 'project_manager',
    phone: '+1 555 0102',
    status: 'active',
    avatar_url: null,
    created_at: now,
  },
  {
    id: 'amelia-client',
    full_name: 'Amelia Carter',
    email: 'amelia@example.com',
    role: 'client',
    phone: '+1 555 0190',
    status: 'active',
    avatar_url: null,
    created_at: now,
  },
  {
    id: 'zain-designer',
    full_name: 'Zain',
    email: 'hafizainali313@gmail.com',
    role: 'employee',
    phone: '+1 555 0103',
    status: 'active',
    avatar_url: null,
    created_at: now,
  },
  {
    id: 'hamza-designer',
    full_name: 'Hamza',
    email: 'hamza@manuscriptheaven.com',
    role: 'employee',
    phone: '+1 555 0104',
    status: 'active',
    avatar_url: null,
    created_at: now,
  },
  {
    id: 'irfan-assistant',
    full_name: 'Irfan',
    email: 'irfan@manuscriptheaven.com',
    role: 'junior_assistant',
    phone: '+1 555 0105',
    status: 'active',
    avatar_url: null,
    created_at: now,
  },
];

export const sampleProjects: Project[] = [
  {
    id: 'project-001',
    project_number: 'MH-1001',
    client_name: 'Amelia Carter',
    client_email: 'amelia@example.com',
    project_title: 'The Quiet Atlas',
    service_type: 'Print + eBook',
    genre: 'Memoir',
    trim_size: '6 x 9',
    page_count: 286,
    word_count: 72000,
    image_count: 12,
    platform: 'Amazon KDP',
    assigned_to: 'zain-designer',
    project_manager: 'atia-manager',
    priority: 'Urgent',
    start_date: addDays(-9),
    due_date: addDays(-1),
    internal_deadline: addDays(-2),
    delivery_date: null,
    status: 'Formatting',
    general_notes: 'Client wants a clean literary layout with chapter ornaments.',
    internal_notes: 'Check widows and orphans before proof export.',
    client_instructions: 'Keep chapter titles simple and elegant.',
    qa_notes: 'Front matter still needs final page numbering review.',
    delivery_notes: '',
    source_file_link: 'https://drive.google.com/example/source-atlas',
    drive_folder_link: 'https://drive.google.com/example/atlas',
    client_brief_link: 'https://docs.google.com/example/atlas-brief',
    proof_pdf_link: '',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 950,
    advance_paid: 500,
    remaining_balance: 450,
    payment_status: 'Partially Paid',
    payment_date: null,
    payment_notes: 'Advance received before layout started.',
    created_by: 'tahir-admin',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-002',
    project_number: 'MH-1002',
    client_name: 'Noah Brooks',
    client_email: 'noah@example.com',
    project_title: 'The Little Star Bakery',
    service_type: "Children's Book",
    genre: 'Children',
    trim_size: '8.5 x 8.5',
    page_count: 36,
    word_count: 1800,
    image_count: 32,
    platform: 'IngramSpark',
    assigned_to: 'hamza-designer',
    project_manager: 'atia-manager',
    priority: 'High',
    start_date: addDays(-3),
    due_date: todayInput(),
    internal_deadline: todayInput(),
    delivery_date: null,
    status: 'Cover Design',
    general_notes: 'Full bleed picture book layout with strong color checks.',
    internal_notes: 'Confirm image resolution before final proof.',
    client_instructions: 'Use playful typography for title pages.',
    qa_notes: '',
    delivery_notes: '',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/bakery',
    client_brief_link: '',
    proof_pdf_link: '',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 1200,
    advance_paid: 1200,
    remaining_balance: 0,
    payment_status: 'Fully Paid',
    payment_date: addDays(-2),
    payment_notes: 'Paid in full.',
    created_by: 'tahir-admin',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-003',
    project_number: 'MH-1003',
    client_name: 'Lena White',
    client_email: 'lena@example.com',
    project_title: 'Founder Notes Workbook',
    service_type: 'Workbook / Journal',
    genre: 'Business',
    trim_size: '7 x 10',
    page_count: 148,
    word_count: 26000,
    image_count: 18,
    platform: 'Amazon KDP',
    assigned_to: 'irfan-assistant',
    project_manager: 'atia-manager',
    priority: 'Normal',
    start_date: addDays(-1),
    due_date: addDays(3),
    internal_deadline: addDays(2),
    delivery_date: null,
    status: 'Client Review',
    general_notes: 'Workbook pages need consistent answer spacing.',
    internal_notes: 'Prepare second proof after client note pass.',
    client_instructions: 'Use clean productivity style.',
    qa_notes: 'Verify margin safety for all worksheet spreads.',
    delivery_notes: '',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/workbook',
    client_brief_link: '',
    proof_pdf_link: 'https://drive.google.com/example/workbook-proof',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 700,
    advance_paid: 350,
    remaining_balance: 350,
    payment_status: 'Advance Paid',
    payment_date: null,
    payment_notes: 'Remaining payment due after client approval.',
    created_by: 'atia-manager',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-004',
    project_number: 'MH-1004',
    client_name: 'Marcus Gray',
    client_email: 'marcus@example.com',
    project_title: 'Wild Rivers',
    service_type: 'eBook Formatting',
    genre: 'Adventure',
    trim_size: 'eBook only',
    page_count: 0,
    word_count: 64000,
    image_count: 4,
    platform: 'Draft2Digital',
    assigned_to: 'zain-designer',
    project_manager: 'atia-manager',
    priority: 'Low',
    start_date: addDays(-20),
    due_date: addDays(-12),
    internal_deadline: addDays(-13),
    delivery_date: addDays(-10),
    status: 'Delivered',
    general_notes: 'Delivered EPUB and MOBI-ready package.',
    internal_notes: '',
    client_instructions: '',
    qa_notes: 'Passed EPUB validation.',
    delivery_notes: 'Final links sent to client.',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/rivers',
    client_brief_link: '',
    proof_pdf_link: '',
    final_print_pdf_link: '',
    final_ebook_link: 'https://drive.google.com/example/rivers-ebook',
    cover_file_link: '',
    other_links: '',
    total_price: 400,
    advance_paid: 400,
    remaining_balance: 0,
    payment_status: 'Fully Paid',
    payment_date: addDays(-11),
    payment_notes: 'Final invoice closed.',
    created_by: 'tahir-admin',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-005',
    project_number: 'MH-1005',
    client_name: 'Priya Shah',
    client_email: 'priya@example.com',
    project_title: 'Quiet Systems Magazine',
    service_type: 'Magazine',
    genre: 'Design',
    trim_size: '8.5 x 11',
    page_count: 64,
    word_count: 18000,
    image_count: 86,
    platform: 'Other',
    assigned_to: 'hamza-designer',
    project_manager: 'atia-manager',
    priority: 'High',
    start_date: addDays(-4),
    due_date: addDays(6),
    internal_deadline: addDays(4),
    delivery_date: null,
    status: 'In Revision',
    general_notes: 'Issue one layout with image-heavy feature spreads.',
    internal_notes: 'Client requested two caption changes and sponsor page update.',
    client_instructions: 'Keep the gold accent consistent across section openers.',
    qa_notes: '',
    delivery_notes: '',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/magazine',
    client_brief_link: '',
    proof_pdf_link: 'https://drive.google.com/example/magazine-proof',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 1450,
    advance_paid: 700,
    remaining_balance: 750,
    payment_status: 'Partially Paid',
    payment_date: null,
    payment_notes: 'Balance due before final files are released.',
    created_by: 'atia-manager',
    created_at: now,
    updated_at: now,
  },
];

export const sampleRevisionNotes: RevisionNote[] = [
  {
    id: 'revision-001',
    project_id: 'project-003',
    revision_number: 1,
    note: 'Client asked for wider writing lines on pages 42 to 57.',
    status: 'Completed',
    added_by: 'atia-manager',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'revision-002',
    project_id: 'project-005',
    revision_number: 2,
    note: 'Update sponsor ad placement and replace two feature images.',
    status: 'In Progress',
    added_by: 'hamza-designer',
    created_at: now,
    updated_at: now,
  },
];

export const sampleProjectNotes: ProjectNote[] = [
  {
    id: 'note-001',
    project_id: 'project-001',
    note_type: 'internal',
    note: 'Need proof export before end of day.',
    added_by: 'atia-manager',
    created_at: now,
  },
  {
    id: 'note-002',
    project_id: 'project-002',
    note_type: 'qa',
    note: 'Check bleed on illustrated spreads.',
    added_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'note-003',
    project_id: 'project-003',
    note_type: 'work',
    note: 'Updated worksheet grid spacing.',
    added_by: 'irfan-assistant',
    created_at: now,
  },
];

export const sampleActivityLogs: ActivityLog[] = [
  {
    id: 'activity-001',
    project_id: 'project-001',
    action: 'Project created',
    old_value: null,
    new_value: 'Formatting started',
    user_id: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'activity-002',
    project_id: 'project-005',
    action: 'Revision added',
    old_value: null,
    new_value: 'Revision 2',
    user_id: 'hamza-designer',
    created_at: now,
  },
  {
    id: 'activity-003',
    project_id: 'project-004',
    action: 'Status changed',
    old_value: 'Ready for Delivery',
    new_value: 'Delivered',
    user_id: 'zain-designer',
    created_at: now,
  },
];

export const sampleNotifications: NotificationItem[] = [
  {
    id: 'notification-001',
    recipient_id: 'zain-designer',
    project_id: 'project-001',
    type: 'project_assigned',
    title: 'Project overdue',
    message: 'The Quiet Atlas is overdue and needs attention.',
    is_read: false,
    created_at: now,
  },
  {
    id: 'notification-002',
    recipient_id: 'hamza-designer',
    project_id: 'project-005',
    type: 'status_changed',
    title: 'Revision added',
    message: 'A new revision note was added to Quiet Systems Magazine.',
    is_read: false,
    created_at: now,
  },
  {
    id: 'notification-003',
    recipient_id: 'amelia-client',
    project_id: 'project-001',
    revision_request_id: 'client-revision-001',
    type: 'revision_status_changed',
    title: 'Revision In Progress',
    message: 'Your revision request for The Quiet Atlas is now in progress.',
    is_read: false,
    created_at: now,
  },
];

export const sampleClientProjectAccess: ClientProjectAccess[] = [
  {
    id: 'client-access-001',
    client_id: 'amelia-client',
    project_id: 'project-001',
    created_at: now,
  },
  {
    id: 'client-access-002',
    client_id: 'amelia-client',
    project_id: 'project-004',
    created_at: now,
  },
];

export const sampleRevisionRequests: RevisionRequest[] = [
  {
    id: 'client-revision-001',
    project_id: 'project-001',
    client_id: 'amelia-client',
    title: 'Chapter opening proof changes',
    description: 'Please adjust the opening pages and check the image placement before the next proof.',
    priority: 'Important',
    status: 'In Progress',
    assigned_to: 'zain-designer',
    submitted_at: addDays(-1),
    completed_at: null,
    created_at: addDays(-1),
    updated_at: now,
  },
];

export const sampleRevisionItems: RevisionItem[] = [
  {
    id: 'client-revision-item-001',
    revision_request_id: 'client-revision-001',
    sort_order: 1,
    page_reference: 'Chapter 2 opening',
    instruction: 'Please move the chapter title slightly lower and keep the ornament centered.',
    status: 'Completed',
    client_attachment_url: '',
    team_response: 'Adjusted in the latest proof.',
    internal_note: 'Handled with master page B.',
    created_at: addDays(-1),
    updated_at: now,
  },
  {
    id: 'client-revision-item-002',
    revision_request_id: 'client-revision-001',
    sort_order: 2,
    page_reference: 'Page 48',
    instruction: 'The image caption should match the style used on page 32.',
    status: 'In Progress',
    client_attachment_url: '',
    team_response: 'Reviewing this with the image spread.',
    internal_note: 'Check source caption doc.',
    created_at: addDays(-1),
    updated_at: now,
  },
];

export const sampleRevisionAttachments: RevisionAttachment[] = [
  {
    id: 'client-revision-attachment-001',
    revision_request_id: 'client-revision-001',
    revision_item_id: null,
    file_name: 'Proof notes.pdf',
    file_url: 'revision-files/amelia-client/project-001/client-revision-001/proof-notes.pdf',
    file_type: 'client_attachment',
    uploaded_by: 'amelia-client',
    created_at: addDays(-1),
  },
];

export const sampleRevisionActivity: RevisionActivity[] = [
  {
    id: 'client-revision-activity-001',
    revision_request_id: 'client-revision-001',
    user_id: 'amelia-client',
    action: 'Revision submitted',
    previous_value: null,
    new_value: 'Chapter opening proof changes',
    created_at: addDays(-1),
  },
  {
    id: 'client-revision-activity-002',
    revision_request_id: 'client-revision-001',
    user_id: 'atia-manager',
    action: 'Status changed',
    previous_value: 'Submitted',
    new_value: 'In Progress',
    created_at: now,
  },
];

export const sampleData = {
  profiles: sampleProfiles,
  projects: sampleProjects,
  revisionNotes: sampleRevisionNotes,
  projectNotes: sampleProjectNotes,
  activityLogs: sampleActivityLogs,
  notifications: sampleNotifications,
  clientProjectAccess: sampleClientProjectAccess,
  revisionRequests: sampleRevisionRequests,
  revisionItems: sampleRevisionItems,
  revisionAttachments: sampleRevisionAttachments,
  revisionActivity: sampleRevisionActivity,
};
