import { addDays, todayInput } from './date';
import type {
  ActivityLog,
  ChatMessage,
  ClientProjectAccess,
  Conversation,
  ConversationMember,
  EmployeeCompensation,
  EmployeeLedgerEntry,
  FinanceTransaction,
  NotificationItem,
  Profile,
  Project,
  ProjectNote,
  RevisionActivity,
  RevisionAttachment,
  RevisionItem,
  RevisionNote,
  RevisionRequest,
  Task,
} from './types';

const now = new Date().toISOString();

export const sampleProfiles: Profile[] = [
  {
    id: 'tahir-admin',
    full_name: 'Tahir',
    email: 'tahir@manuscriptheaven.com',
    role: 'admin',
    phone: '+1 555 0101',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: now,
  },
  {
    id: 'atia-manager',
    full_name: 'Atia',
    email: 'atia@manuscriptheaven.com',
    role: 'project_manager',
    phone: '+1 555 0102',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    created_at: now,
  },
  {
    id: 'amelia-client',
    full_name: 'Amelia Carter',
    email: 'amelia@example.com',
    role: 'client',
    phone: '+1 555 0190',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    created_at: now,
  },
  {
    id: 'zain-designer',
    full_name: 'Zain',
    email: 'hafizainali313@gmail.com',
    role: 'employee',
    phone: '+1 555 0103',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    created_at: now,
  },
  {
    id: 'hamza-designer',
    full_name: 'Hamza',
    email: 'hamza@manuscriptheaven.com',
    role: 'employee',
    phone: '+1 555 0104',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    created_at: now,
  },
  {
    id: 'irfan-assistant',
    full_name: 'Irfan',
    email: 'irfan@manuscriptheaven.com',
    role: 'junior_assistant',
    phone: '+1 555 0105',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    created_at: now,
  },
];

export const sampleProjects: Project[] = [
  {
    id: 'project-001',
    project_number: 'MH-1001',
    client_name: 'Amelia Carter',
    client_email: 'amelia@example.com',
    project_title: 'The Quiet Atlas',
    service_type: 'Print + eBook',
    genre: 'Memoir',
    trim_size: '6 x 9',
    page_count: 286,
    word_count: 72000,
    image_count: 12,
    platform: 'Amazon KDP',
    assigned_to: 'zain-designer',
    project_manager: 'atia-manager',
    priority: 'Urgent',
    start_date: addDays(-9),
    due_date: addDays(2),
    internal_deadline: addDays(1),
    delivery_date: null,
    status: 'In Progress',
    current_stage: 'Print Version',
    stage_status: 'ACTIVE',
    waiting_on: 'Manuscript Heaven',
    timeline_status: 'Active',
    stage_started_at: addDays(-3),
    stage_due_at: addDays(2),
    design_concept_approval_date: addDays(-3),
    general_notes: 'Client wants a clean literary layout with chapter ornaments.',
    internal_notes: 'Check widows and orphans before proof export.',
    client_instructions: 'Keep chapter titles simple and elegant.',
    qa_notes: 'Front matter still needs final page numbering review.',
    delivery_notes: '',
    source_file_link: 'https://drive.google.com/example/source-atlas',
    drive_folder_link: 'https://drive.google.com/example/atlas',
    client_brief_link: 'https://docs.google.com/example/atlas-brief',
    proof_pdf_link: '',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 950,
    advance_paid: 500,
    remaining_balance: 450,
    payment_status: 'Partially Paid',
    payment_date: null,
    payment_notes: 'Advance received before layout started.',
    created_by: 'tahir-admin',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-002',
    project_number: 'MH-1002',
    client_name: 'Noah Brooks',
    client_email: 'noah@example.com',
    project_title: 'The Little Star Bakery',
    service_type: "Children's Book",
    genre: 'Children',
    trim_size: '8.5 x 8.5',
    page_count: 36,
    word_count: 1800,
    image_count: 32,
    platform: 'IngramSpark',
    assigned_to: 'hamza-designer',
    project_manager: 'atia-manager',
    priority: 'High',
    start_date: addDays(-3),
    due_date: todayInput(),
    internal_deadline: todayInput(),
    delivery_date: null,
    status: 'Awaiting Client Approval',
    current_stage: 'Concept Approval',
    stage_status: 'PAUSED_CLIENT_REVIEW',
    waiting_on: 'Client',
    timeline_status: 'Paused',
    design_concept_submitted_date: addDays(-1),
    general_notes: 'Full bleed picture book layout with strong color checks.',
    internal_notes: 'Confirm image resolution before final proof.',
    client_instructions: 'Use playful typography for title pages.',
    qa_notes: '',
    delivery_notes: '',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/bakery',
    client_brief_link: '',
    proof_pdf_link: '',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 1200,
    advance_paid: 1200,
    remaining_balance: 0,
    payment_status: 'Fully Paid',
    payment_date: addDays(-2),
    payment_notes: 'Paid in full.',
    created_by: 'tahir-admin',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-003',
    project_number: 'MH-1003',
    client_name: 'Lena White',
    client_email: 'lena@example.com',
    project_title: 'Founder Notes Workbook',
    service_type: 'Workbook / Journal',
    genre: 'Business',
    trim_size: '7 x 10',
    page_count: 148,
    word_count: 26000,
    image_count: 18,
    platform: 'Amazon KDP',
    assigned_to: 'irfan-assistant',
    project_manager: 'atia-manager',
    priority: 'Normal',
    start_date: addDays(-1),
    due_date: addDays(2),
    internal_deadline: addDays(2),
    delivery_date: null,
    status: 'In Revision',
    current_stage: 'Concept Approval',
    stage_status: 'REVISION_ACTIVE',
    waiting_on: 'Manuscript Heaven',
    timeline_status: 'Revision Required',
    revision_count: 1,
    stage_started_at: todayInput(),
    stage_due_at: addDays(2),
    general_notes: 'Workbook pages need consistent answer spacing.',
    internal_notes: 'Prepare second proof after client note pass.',
    client_instructions: 'Use clean productivity style.',
    qa_notes: 'Verify margin safety for all worksheet spreads.',
    delivery_notes: '',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/workbook',
    client_brief_link: '',
    proof_pdf_link: 'https://drive.google.com/example/workbook-proof',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 700,
    advance_paid: 350,
    remaining_balance: 350,
    payment_status: 'Advance Paid',
    payment_date: null,
    payment_notes: 'Remaining payment due after client approval.',
    created_by: 'atia-manager',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-004',
    project_number: 'MH-1004',
    client_name: 'Marcus Gray',
    client_email: 'marcus@example.com',
    project_title: 'Wild Rivers',
    service_type: 'eBook Formatting',
    genre: 'Adventure',
    trim_size: 'eBook only',
    page_count: 0,
    word_count: 64000,
    image_count: 4,
    platform: 'Draft2Digital',
    assigned_to: 'zain-designer',
    project_manager: 'atia-manager',
    priority: 'Low',
    start_date: addDays(-20),
    due_date: addDays(-12),
    internal_deadline: addDays(-13),
    delivery_date: addDays(-10),
    final_delivery_date: addDays(-10),
    status: 'Completed',
    current_stage: 'Final Delivery',
    stage_status: 'COMPLETED',
    waiting_on: 'None',
    timeline_status: 'Completed',
    general_notes: 'Delivered EPUB and MOBI-ready package.',
    internal_notes: '',
    client_instructions: '',
    qa_notes: 'Passed EPUB validation.',
    delivery_notes: 'Final links sent to client.',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/rivers',
    client_brief_link: '',
    proof_pdf_link: '',
    final_print_pdf_link: '',
    final_ebook_link: 'https://drive.google.com/example/rivers-ebook',
    cover_file_link: '',
    other_links: '',
    total_price: 400,
    advance_paid: 400,
    remaining_balance: 0,
    payment_status: 'Fully Paid',
    payment_date: addDays(-11),
    payment_notes: 'Final invoice closed.',
    created_by: 'tahir-admin',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'project-005',
    project_number: 'MH-1005',
    client_name: 'Priya Shah',
    client_email: 'priya@example.com',
    project_title: 'Quiet Systems Magazine',
    service_type: 'Magazine',
    genre: 'Design',
    trim_size: '8.5 x 11',
    page_count: 64,
    word_count: 18000,
    image_count: 86,
    platform: 'Other',
    assigned_to: 'hamza-designer',
    project_manager: 'atia-manager',
    priority: 'High',
    start_date: addDays(-4),
    due_date: addDays(6),
    internal_deadline: addDays(4),
    delivery_date: null,
    status: 'In Revision',
    current_stage: 'Print Approval',
    stage_status: 'REVISION_ACTIVE',
    waiting_on: 'Manuscript Heaven',
    timeline_status: 'Revision Required',
    revision_count: 2,
    stage_started_at: addDays(-1),
    stage_due_at: addDays(2),
    general_notes: 'Issue one layout with image-heavy feature spreads.',
    internal_notes: 'Client requested two caption changes and sponsor page update.',
    client_instructions: 'Keep the gold accent consistent across section openers.',
    qa_notes: '',
    delivery_notes: '',
    source_file_link: '',
    drive_folder_link: 'https://drive.google.com/example/magazine',
    client_brief_link: '',
    proof_pdf_link: 'https://drive.google.com/example/magazine-proof',
    final_print_pdf_link: '',
    final_ebook_link: '',
    cover_file_link: '',
    other_links: '',
    total_price: 1450,
    advance_paid: 700,
    remaining_balance: 750,
    payment_status: 'Partially Paid',
    payment_date: null,
    payment_notes: 'Balance due before final files are released.',
    created_by: 'atia-manager',
    created_at: now,
    updated_at: now,
  },
];

export const sampleRevisionNotes: RevisionNote[] = [
  {
    id: 'revision-001',
    project_id: 'project-003',
    revision_number: 1,
    note: 'Client asked for wider writing lines on pages 42 to 57.',
    status: 'Completed',
    added_by: 'atia-manager',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'revision-002',
    project_id: 'project-005',
    revision_number: 2,
    note: 'Update sponsor ad placement and replace two feature images.',
    status: 'In Progress',
    added_by: 'hamza-designer',
    created_at: now,
    updated_at: now,
  },
];

export const sampleProjectNotes: ProjectNote[] = [
  {
    id: 'note-001',
    project_id: 'project-001',
    note_type: 'internal',
    note: 'Need proof export before end of day.',
    added_by: 'atia-manager',
    created_at: now,
  },
  {
    id: 'note-002',
    project_id: 'project-002',
    note_type: 'qa',
    note: 'Check bleed on illustrated spreads.',
    added_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'note-003',
    project_id: 'project-003',
    note_type: 'work',
    note: 'Updated worksheet grid spacing.',
    added_by: 'irfan-assistant',
    created_at: now,
  },
];

export const sampleActivityLogs: ActivityLog[] = [
  {
    id: 'activity-001',
    project_id: 'project-001',
    action: 'Project created',
    old_value: null,
    new_value: 'Formatting started',
    user_id: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'activity-002',
    project_id: 'project-005',
    action: 'Revision added',
    old_value: null,
    new_value: 'Revision 2',
    user_id: 'hamza-designer',
    created_at: now,
  },
  {
    id: 'activity-003',
    project_id: 'project-004',
    action: 'Status changed',
    old_value: 'Ready for Delivery',
    new_value: 'Delivered',
    user_id: 'zain-designer',
    created_at: now,
  },
];

export const sampleNotifications: NotificationItem[] = [
  {
    id: 'notification-001',
    recipient_id: 'zain-designer',
    project_id: 'project-001',
    type: 'project_assigned',
    title: 'Project overdue',
    message: 'The Quiet Atlas is overdue and needs attention.',
    is_read: false,
    created_at: now,
  },
  {
    id: 'notification-002',
    recipient_id: 'hamza-designer',
    project_id: 'project-005',
    type: 'status_changed',
    title: 'Revision added',
    message: 'A new revision note was added to Quiet Systems Magazine.',
    is_read: false,
    created_at: now,
  },
  {
    id: 'notification-003',
    recipient_id: 'amelia-client',
    project_id: 'project-001',
    revision_request_id: 'client-revision-001',
    type: 'revision_status_changed',
    title: 'Revision In Progress',
    message: 'Your revision request for The Quiet Atlas is now in progress.',
    is_read: false,
    created_at: now,
  },
];

export const sampleClientProjectAccess: ClientProjectAccess[] = [
  {
    id: 'client-access-001',
    client_id: 'amelia-client',
    project_id: 'project-001',
    created_at: now,
  },
  {
    id: 'client-access-002',
    client_id: 'amelia-client',
    project_id: 'project-004',
    created_at: now,
  },
];

export const sampleTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Export proof for The Quiet Atlas',
    description: 'Prepare the latest PDF proof and attach it to the project before client review.',
    project_id: 'project-001',
    assigned_to: 'zain-designer',
    created_by: 'atia-manager',
    status: 'In Progress',
    priority: 'High',
    due_date: todayInput(),
    completed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'task-002',
    title: 'Check picture book bleed',
    description: 'Review all illustrated spreads for bleed and margin safety.',
    project_id: 'project-002',
    assigned_to: 'hamza-designer',
    created_by: 'tahir-admin',
    status: 'To Do',
    priority: 'Normal',
    due_date: addDays(1),
    completed_at: null,
    created_at: now,
    updated_at: now,
  },
];

export const sampleRevisionRequests: RevisionRequest[] = [
  {
    id: 'client-revision-001',
    project_id: 'project-001',
    client_id: 'amelia-client',
    title: 'Chapter opening proof changes',
    description: 'Please adjust the opening pages and check the image placement before the next proof.',
    instructions: 'Please adjust the opening pages and check the image placement before the next proof.',
    team_response: null,
    priority: 'Important',
    status: 'In Progress',
    assigned_to: 'zain-designer',
    submitted_at: addDays(-1),
    completed_at: null,
    created_at: addDays(-1),
    updated_at: now,
  },
];

export const sampleRevisionItems: RevisionItem[] = [
  {
    id: 'client-revision-item-001',
    revision_request_id: 'client-revision-001',
    sort_order: 1,
    page_reference: 'Chapter 2 opening',
    instruction: 'Please move the chapter title slightly lower and keep the ornament centered.',
    status: 'Completed',
    client_attachment_url: '',
    team_response: 'Adjusted in the latest proof.',
    internal_note: 'Handled with master page B.',
    created_at: addDays(-1),
    updated_at: now,
  },
  {
    id: 'client-revision-item-002',
    revision_request_id: 'client-revision-001',
    sort_order: 2,
    page_reference: 'Page 48',
    instruction: 'The image caption should match the style used on page 32.',
    status: 'In Progress',
    client_attachment_url: '',
    team_response: 'Reviewing this with the image spread.',
    internal_note: 'Check source caption doc.',
    created_at: addDays(-1),
    updated_at: now,
  },
];

export const sampleRevisionAttachments: RevisionAttachment[] = [
  {
    id: 'client-revision-attachment-001',
    revision_request_id: 'client-revision-001',
    revision_item_id: null,
    file_name: 'Proof notes.pdf',
    file_url: 'revision-files/amelia-client/project-001/client-revision-001/proof-notes.pdf',
    file_type: 'client_attachment',
    uploaded_by: 'amelia-client',
    created_at: addDays(-1),
  },
];

export const sampleRevisionActivity: RevisionActivity[] = [
  {
    id: 'client-revision-activity-001',
    revision_request_id: 'client-revision-001',
    user_id: 'amelia-client',
    action: 'Revision submitted',
    previous_value: null,
    new_value: 'Chapter opening proof changes',
    created_at: addDays(-1),
  },
  {
    id: 'client-revision-activity-002',
    revision_request_id: 'client-revision-001',
    user_id: 'atia-manager',
    action: 'Status changed',
    previous_value: 'Submitted',
    new_value: 'In Progress',
    created_at: now,
  },
];

export const sampleConversations: Conversation[] = [
  {
    id: 'channel-general',
    type: 'team_channel',
    name: 'general',
    created_by: 'tahir-admin',
    created_at: addDays(-10),
    updated_at: now,
  },
  {
    id: 'channel-formatting',
    type: 'team_channel',
    name: 'formatting',
    created_by: 'tahir-admin',
    created_at: addDays(-10),
    updated_at: now,
  },
  {
    id: 'channel-covers',
    type: 'team_channel',
    name: 'covers',
    created_by: 'tahir-admin',
    created_at: addDays(-10),
    updated_at: now,
  },
  {
    id: 'channel-qc',
    type: 'team_channel',
    name: 'qc',
    created_by: 'tahir-admin',
    created_at: addDays(-10),
    updated_at: now,
  },
  {
    id: 'dm-tahir-zain',
    type: 'dm',
    created_by: 'tahir-admin',
    created_at: addDays(-5),
    updated_at: now,
  },
  {
    id: 'conv-project-001-internal',
    type: 'project_internal',
    project_id: 'project-001',
    created_by: 'tahir-admin',
    created_at: addDays(-7),
    updated_at: now,
  },
  {
    id: 'conv-project-001-client',
    type: 'project_client',
    project_id: 'project-001',
    created_by: 'tahir-admin',
    created_at: addDays(-7),
    updated_at: now,
  },
];

export const sampleConversationMembers: ConversationMember[] = [
  { id: 'cm-1', conversation_id: 'dm-tahir-zain', user_id: 'tahir-admin', last_read_at: now, created_at: addDays(-5) },
  { id: 'cm-2', conversation_id: 'dm-tahir-zain', user_id: 'zain-designer', last_read_at: addDays(-1), created_at: addDays(-5) },
];

export const sampleMessages: ChatMessage[] = [
  {
    id: 'msg-gen-1',
    conversation_id: 'channel-general',
    sender_id: 'tahir-admin',
    body: 'Good morning team! Welcome to the new communication center. Let us make sure all client communications stay documented here.',
    created_at: addDays(-2),
    updated_at: addDays(-2),
  },
  {
    id: 'msg-gen-2',
    conversation_id: 'channel-general',
    sender_id: 'zain-designer',
    body: 'Awesome! This will make tracking book revisions and margins so much easier.',
    created_at: addDays(-2),
    updated_at: addDays(-2),
  },
  {
    id: 'msg-dm-1',
    conversation_id: 'dm-tahir-zain',
    sender_id: 'tahir-admin',
    body: '@Zain Please check the margins on Book 3 before sending it to the client.',
    created_at: addDays(-1),
    updated_at: addDays(-1),
  },
  {
    id: 'msg-dm-2',
    conversation_id: 'dm-tahir-zain',
    sender_id: 'zain-designer',
    body: 'Sure, working on it right now. Checking page 42 margins.',
    created_at: addDays(-1),
    updated_at: addDays(-1),
  },
  {
    id: 'msg-p1-int-1',
    conversation_id: 'conv-project-001-internal',
    sender_id: 'tahir-admin',
    body: 'Client requested extra layout changes on Chapter 4. Let us finalize design internal check before sending revision.',
    created_at: addDays(-1),
    updated_at: addDays(-1),
  },
  {
    id: 'msg-p1-cli-1',
    conversation_id: 'conv-project-001-client',
    sender_id: 'tahir-admin',
    body: 'Hi Amelia! We have uploaded the revised Print PDF Proof for your review.',
    created_at: addDays(-1),
    updated_at: addDays(-1),
  },
  {
    id: 'msg-p1-cli-2',
    conversation_id: 'conv-project-001-client',
    sender_id: 'amelia-client',
    body: 'Thank you! The interior looks great. I approved the print version.',
    created_at: now,
    updated_at: now,
  },
];

export const sampleEmployeeCompensation: EmployeeCompensation[] = [
  {
    employee_id: 'atia-manager',
    monthly_salary: 500,
    per_project_rate: 50,
    salary_type: 'Monthly',
    default_currency: 'USD',
    joining_date: '2025-01-15',
    responsibilities: 'Project Management & Quality Check',
    performance_rating: 96,
    updated_at: now,
  },
  {
    employee_id: 'zain-designer',
    monthly_salary: 400,
    per_project_rate: 50,
    salary_type: 'Monthly',
    default_currency: 'USD',
    joining_date: '2025-02-01',
    responsibilities: 'Interior Typesetting & Book Formatting',
    performance_rating: 94,
    updated_at: now,
  },
  {
    employee_id: 'hamza-designer',
    monthly_salary: 350,
    per_project_rate: 40,
    salary_type: 'Monthly',
    default_currency: 'USD',
    joining_date: '2025-03-10',
    responsibilities: 'Cover Design & Illustration Layout',
    performance_rating: 92,
    updated_at: now,
  },
  {
    employee_id: 'irfan-assistant',
    monthly_salary: 250,
    per_project_rate: 30,
    salary_type: 'Monthly',
    default_currency: 'USD',
    joining_date: '2025-05-01',
    responsibilities: 'eBook Conversion & Quality Proofing',
    performance_rating: 88,
    updated_at: now,
  },
];

export const sampleEmployeeLedger: EmployeeLedgerEntry[] = [
  // --- AUGUST 2026 ENTRIES ---
  // Atia (Base $500 + Project $100 = $600 Payable; Paid $400; $200 Outstanding)
  {
    id: 'el-001',
    employee_id: 'atia-manager',
    entry_type: 'Project Payment',
    amount: 100,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: null,
    project_id: 'project-001',
    notes: 'The Quiet Atlas project management commission',
    paid_at: '2026-08-08',
    created_at: '2026-08-08T10:00:00Z',
  },
  {
    id: 'el-002',
    employee_id: 'atia-manager',
    entry_type: 'Payment',
    amount: 400,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-ATIA-08A',
    project_id: null,
    notes: 'August partial salary disbursement',
    paid_at: '2026-08-10',
    created_at: '2026-08-10T10:00:00Z',
  },

  // Zain (Base $400 + Project $100 - Deduction $20 = $480 Payable; Paid $300 + $180 = $480; $0 Outstanding -> Paid)
  {
    id: 'el-003',
    employee_id: 'zain-designer',
    entry_type: 'Project Payment',
    amount: 100,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: null,
    project_id: 'project-001',
    notes: 'Interior typesetting milestone commission',
    paid_at: '2026-08-05',
    created_at: '2026-08-05T10:00:00Z',
  },
  {
    id: 'el-004',
    employee_id: 'zain-designer',
    entry_type: 'Deduction',
    amount: 20,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: null,
    project_id: null,
    notes: 'Software asset adjustment',
    paid_at: '2026-08-07',
    created_at: '2026-08-07T10:00:00Z',
  },
  {
    id: 'el-005',
    employee_id: 'zain-designer',
    entry_type: 'Payment',
    amount: 300,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-ZAIN-08A',
    project_id: null,
    notes: 'August 1st payment installment',
    paid_at: '2026-08-10',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'el-006',
    employee_id: 'zain-designer',
    entry_type: 'Payment',
    amount: 180,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: 'Wise',
    reference: 'TRX-ZAIN-08B',
    project_id: null,
    notes: 'August final salary balance cleared',
    paid_at: '2026-08-18',
    created_at: '2026-08-18T10:00:00Z',
  },

  // Hamza (Base $350 + Bonus $50 = $400 Payable; Advance $50; Paid $200; $200 Outstanding)
  {
    id: 'el-007',
    employee_id: 'hamza-designer',
    entry_type: 'Bonus',
    amount: 50,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: null,
    project_id: 'project-002',
    notes: 'Quality illustration reward',
    paid_at: '2026-08-04',
    created_at: '2026-08-04T10:00:00Z',
  },
  {
    id: 'el-008',
    employee_id: 'hamza-designer',
    entry_type: 'Advance',
    amount: 50,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: 'Cash',
    project_id: null,
    notes: 'Mid-month personal advance',
    paid_at: '2026-08-06',
    created_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'el-009',
    employee_id: 'hamza-designer',
    entry_type: 'Payment',
    amount: 200,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-HAMZA-08',
    project_id: null,
    notes: 'August partial salary payment',
    paid_at: '2026-08-12',
    created_at: '2026-08-12T10:00:00Z',
  },

  // Irfan (Base $250; Paid $250; $0 Outstanding -> Paid)
  {
    id: 'el-010',
    employee_id: 'irfan-assistant',
    entry_type: 'Payment',
    amount: 250,
    currency: 'USD',
    salary_month: '2026-08-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-IRFAN-08',
    project_id: null,
    notes: 'August salary payment in full',
    paid_at: '2026-08-08',
    created_at: '2026-08-08T10:00:00Z',
  },

  // --- JULY 2026 ENTRIES (For Multi-Month testing) ---
  {
    id: 'el-011',
    employee_id: 'atia-manager',
    entry_type: 'Payment',
    amount: 500,
    currency: 'USD',
    salary_month: '2026-07-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-ATIA-07',
    project_id: null,
    notes: 'July salary cleared in full',
    paid_at: '2026-07-10',
    created_at: '2026-07-10T10:00:00Z',
  },
  {
    id: 'el-012',
    employee_id: 'zain-designer',
    entry_type: 'Payment',
    amount: 400,
    currency: 'USD',
    salary_month: '2026-07-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-ZAIN-07',
    project_id: null,
    notes: 'July salary cleared in full',
    paid_at: '2026-07-10',
    created_at: '2026-07-10T10:00:00Z',
  },
  {
    id: 'el-013',
    employee_id: 'hamza-designer',
    entry_type: 'Payment',
    amount: 350,
    currency: 'USD',
    salary_month: '2026-07-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-HAMZA-07',
    project_id: null,
    notes: 'July salary cleared in full',
    paid_at: '2026-07-10',
    created_at: '2026-07-10T10:00:00Z',
  },
  {
    id: 'el-014',
    employee_id: 'irfan-assistant',
    entry_type: 'Payment',
    amount: 250,
    currency: 'USD',
    salary_month: '2026-07-01',
    payment_method: 'Bank Transfer',
    reference: 'TRX-IRFAN-07',
    project_id: null,
    notes: 'July salary cleared in full',
    paid_at: '2026-07-10',
    created_at: '2026-07-10T10:00:00Z',
  },
];

export const sampleFinanceTransactions: FinanceTransaction[] = [
  {
    id: 'ftx-001',
    type: 'income',
    category: 'Project Payment',
    description: 'QAI Reformatting Milestone Payment',
    amount: 100,
    original_amount: 100,
    currency: 'USD',
    exchange_rate: 280,
    amount_pkr: 28000,
    base_amount_pkr: 28000,
    transaction_date: '2026-08-17',
    client_name: 'BCH',
    payment_method: 'Bank Transfer',
    payment_status: 'Paid',
    notes: 'QAI Milestone 1 received in USD',
    created_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'ftx-002',
    type: 'expense',
    category: 'Software',
    description: 'Adobe Creative Cloud',
    vendor: 'Adobe',
    amount: 60,
    original_amount: 60,
    currency: 'USD',
    exchange_rate: 280,
    amount_pkr: 16800,
    base_amount_pkr: 16800,
    transaction_date: '2026-08-17',
    payment_method: 'Card',
    payment_status: 'Paid',
    notes: 'Monthly design team license',
    created_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'ftx-003',
    type: 'income',
    category: 'Book Formatting',
    description: 'Book Formatting Project Payment',
    amount: 25000,
    original_amount: 25000,
    currency: 'PKR',
    exchange_rate: 1,
    amount_pkr: 25000,
    base_amount_pkr: 25000,
    transaction_date: '2026-08-16',
    client_name: 'Shara',
    payment_method: 'Bank Transfer',
    payment_status: 'Paid',
    notes: 'Local bank transfer in PKR',
    created_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'ftx-004',
    type: 'expense',
    category: 'Internet',
    description: 'Office Internet Connection',
    vendor: 'PTCL',
    amount: 8500,
    original_amount: 8500,
    currency: 'PKR',
    exchange_rate: 1,
    amount_pkr: 8500,
    base_amount_pkr: 8500,
    transaction_date: '2026-08-15',
    payment_method: 'Easypaisa',
    payment_status: 'Paid',
    notes: 'Office fiber connection',
    created_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'ftx-005',
    type: 'income',
    category: 'Book Formatting',
    description: 'BCH – Book Formatting Advance',
    amount: 20000,
    original_amount: 20000,
    currency: 'PKR',
    exchange_rate: 1,
    amount_pkr: 20000,
    base_amount_pkr: 20000,
    transaction_date: '2026-08-15',
    client_name: 'BCH',
    payment_method: 'JazzCash',
    payment_status: 'Partially Paid',
    notes: 'Partial advance payment in PKR',
    created_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'ftx-006',
    type: 'expense',
    category: 'Freelancer',
    description: 'Freelance Cover Designer Assistance',
    vendor: 'Design Studio',
    amount: 50,
    original_amount: 50,
    currency: 'USD',
    exchange_rate: 280,
    amount_pkr: 14000,
    base_amount_pkr: 14000,
    transaction_date: '2026-08-12',
    payment_method: 'PayPal',
    payment_status: 'Paid',
    notes: 'Contract design work',
    created_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'ftx-007',
    type: 'income',
    category: 'Other Services',
    description: 'Fiverr – Novel Formatting',
    amount: 300,
    original_amount: 300,
    currency: 'USD',
    exchange_rate: 280,
    amount_pkr: 84000,
    base_amount_pkr: 84000,
    transaction_date: '2026-08-10',
    client_name: 'Fiverr',
    payment_method: 'Upwork',
    payment_status: 'Paid',
    notes: 'Fiverr direct payout',
    created_by: 'tahir-admin',
    created_at: now,
  },
  {
    id: 'ftx-008',
    type: 'expense',
    category: 'Office',
    description: 'Office Stationery & Supplies',
    vendor: 'Stationery World',
    amount: 5000,
    original_amount: 5000,
    currency: 'PKR',
    exchange_rate: 1,
    amount_pkr: 5000,
    base_amount_pkr: 5000,
    transaction_date: '2026-08-05',
    payment_method: 'Cash',
    payment_status: 'Paid',
    notes: 'Printer paper & supplies',
    created_by: 'tahir-admin',
    created_at: now,
  },
];

export const sampleData = {
  profiles: sampleProfiles,
  projects: sampleProjects,
  revisionNotes: sampleRevisionNotes,
  projectNotes: sampleProjectNotes,
  activityLogs: sampleActivityLogs,
  notifications: sampleNotifications,
  clientProjectAccess: sampleClientProjectAccess,
  tasks: sampleTasks,
  revisionRequests: sampleRevisionRequests,
  revisionItems: sampleRevisionItems,
  revisionAttachments: sampleRevisionAttachments,
  revisionActivity: sampleRevisionActivity,
  conversations: sampleConversations,
  conversationMembers: sampleConversationMembers,
  messages: sampleMessages,
  messageAttachments: [],
  messageReactions: [],
  messageMentions: [],
  employeeCompensation: sampleEmployeeCompensation,
  employeeLedger: sampleEmployeeLedger,
  financeTransactions: sampleFinanceTransactions,
};


