import { useMemo, useState } from 'react';
import { DollarSign, Mail, Phone, TrendingUp, Users } from 'lucide-react';
import { RoleBadge } from '../components/Badges';
import { Button, Card, Field, Modal, SelectField, TextareaField } from '../components/ui';
import { closedStatuses } from '../lib/constants';
import { isOverdue } from '../lib/date';
import { firstName, initials, isClientRole } from '../lib/utils';
import { useCurrency } from '../lib/currency';
import type { EmployeeCompensation, EmployeeLedgerEntry, Profile, Project, Task } from '../lib/types';

type Tab = 'overview' | 'employees' | 'payroll' | 'workload';

function employeeMetrics(profile: Profile, projects: Project[], tasks: Task[]) {
  const assigned = projects.filter((project) => project.assigned_to === profile.id);
  const active = assigned.filter((project) => !closedStatuses.includes(project.status));
  const completed = assigned.filter((project) => closedStatuses.includes(project.status));
  const overdue = active.filter(isOverdue);
  const employeeTasks = tasks.filter((task) => task.assigned_to === profile.id);
  const doneTasks = employeeTasks.filter((task) => task.status === 'Done');
  const quality = assigned.length ? Math.round(((assigned.length - overdue.length) / assigned.length) * 100) : 100;
  const performance = Math.max(0, Math.round(quality * 0.55 + (employeeTasks.length ? (doneTasks.length / employeeTasks.length) * 45 : 45)));
  return { assigned, active, completed, overdue, employeeTasks, doneTasks, quality, performance };
}

function ledgerSummary(employeeId: string, compensation: EmployeeCompensation | undefined, ledger: EmployeeLedgerEntry[]) {
  const entries = ledger.filter((entry) => entry.employee_id === employeeId);
  const amount = (type: EmployeeLedgerEntry['entry_type']) => entries.filter((entry) => entry.entry_type === type).reduce((sum, entry) => sum + Number(entry.amount), 0);
  const earnings = amount('Project Payment') + amount('Bonus') + amount('Other');
  const advances = amount('Advance');
  const deductions = amount('Deduction');
  const payable = Number(compensation?.monthly_salary || 0) + earnings - deductions;
  const paid = amount('Payment') + advances;
  return { payable, earnings, advances, deductions, paid, due: Math.max(0, payable - paid) };
}

export function TeamPage({ profiles, projects, tasks, compensation, ledger, canManagePayroll, onAddLedgerEntry }: {
  profiles: Profile[]; projects: Project[]; tasks: Task[]; compensation: EmployeeCompensation[]; ledger: EmployeeLedgerEntry[]; canManagePayroll: boolean; onAddLedgerEntry: (entry: Omit<EmployeeLedgerEntry, 'id' | 'created_at'>) => Promise<void>;
}) {
  const { formatMoney } = useCurrency();
  const [tab, setTab] = useState<Tab>('overview');
  const [payrollMonth, setPayrollMonth] = useState(new Date().toISOString().slice(0, 7));
  const [ledgerEmployeeId, setLedgerEmployeeId] = useState<string | null>(null);
  const [showEntryForm, setShowEntryForm] = useState(false);
  const team = profiles.filter((profile) => !isClientRole(profile.role));
  const rows = useMemo(() => team.map((profile) => ({ profile, metrics: employeeMetrics(profile, projects, tasks), compensation: compensation.find((item) => item.employee_id === profile.id) })), [team, projects, tasks, compensation]);
  const monthLedger = ledger.filter((entry) => (entry.salary_month || entry.paid_at || '').slice(0, 7) === payrollMonth);
  const totalPayroll = rows.reduce((sum, row) => sum + ledgerSummary(row.profile.id, row.compensation, monthLedger).payable, 0);
  const totalDue = rows.reduce((sum, row) => sum + ledgerSummary(row.profile.id, row.compensation, monthLedger).due, 0);
  const tabs: Array<{ id: Tab; label: string }> = [{ id: 'overview', label: 'Team Overview' }, { id: 'employees', label: 'Employees' }, { id: 'workload', label: 'Workload' }, ...(canManagePayroll ? [{ id: 'payroll' as Tab, label: 'Payroll & Dues' }] : [])];

  return <div className="space-y-6">
    <div className="flex flex-wrap gap-2">{tabs.map((item) => <Button key={item.id} type="button" variant={tab === item.id ? 'primary' : 'secondary'} onClick={() => setTab(item.id)}>{item.label}</Button>)}</div>
    {tab === 'overview' ? <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        <Stat label="Total Employees" value={team.length} icon={Users} /><Stat label="Active Employees" value={team.filter((p) => p.status !== 'inactive').length} icon={Users} />
        <Stat label="Projects Assigned" value={rows.reduce((sum, row) => sum + row.metrics.active.length, 0)} icon={TrendingUp} /><Stat label="Monthly Payroll" value={formatMoney(totalPayroll, 'USD')} icon={DollarSign} /><Stat label="Outstanding Dues" value={formatMoney(totalDue, 'USD')} icon={DollarSign} />
      </section>
      <PerformanceTable rows={rows} />
    </> : null}
    {tab === 'employees' ? <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rows.map(({ profile, metrics, compensation: pay }) => <Card key={profile.id}><div className="flex items-start gap-4"><div className="grid h-14 w-14 place-items-center rounded-lg bg-gold/20 text-lg font-bold">{initials(firstName(profile.full_name))}</div><div className="min-w-0"><h3 className="font-display text-xl font-semibold">{profile.full_name}</h3><RoleBadge role={profile.role} /></div></div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-sm"><Metric label="Active" value={metrics.active.length}/><Metric label="Completed" value={metrics.completed.length}/><Metric label="Performance" value={`${metrics.performance}%`}/></div><div className="mt-5 space-y-2 text-sm text-muted"><p className="flex gap-2"><Mail className="h-4 w-4"/>{profile.email}</p>{profile.phone ? <p className="flex gap-2"><Phone className="h-4 w-4"/>{profile.phone}</p> : null}<p>Monthly: <strong className="text-ink">{formatMoney(pay?.monthly_salary || 0, 'USD')}</strong> · Per Project: <strong className="text-ink">{formatMoney(pay?.per_project_rate || 0, 'USD')}</strong></p><p>Responsibilities: {pay?.responsibilities || 'Not set'}</p></div></Card>)}</section> : null}
    {tab === 'workload' ? <section className="space-y-4">{rows.map(({ profile, metrics }) => <Card key={profile.id}><div className="flex items-center justify-between"><div><h3 className="font-semibold">{profile.full_name}</h3><p className="text-sm text-muted">{metrics.active.length} active projects · {metrics.doneTasks.length}/{metrics.employeeTasks.length} tasks complete</p></div><span className="font-bold text-danger">{metrics.overdue.length} overdue</span></div><div className="mt-4 grid gap-2 md:grid-cols-3">{metrics.active.map((project) => <div key={project.id} className="rounded-md bg-ivory p-3 text-sm"><strong>{project.project_title}</strong><p className="text-muted">{project.current_stage || project.status} · Due {project.due_date}</p></div>) || <p className="text-sm text-muted">No active projects.</p>}</div></Card>)}</section> : null}
    {tab === 'payroll' && canManagePayroll ? <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total Payroll" value={formatMoney(totalPayroll, 'USD')} icon={DollarSign}/><Stat label="Total Paid" value={formatMoney(rows.reduce((sum, row) => sum + ledgerSummary(row.profile.id, row.compensation, monthLedger).paid, 0), 'USD')} icon={DollarSign}/><Stat label="Outstanding" value={formatMoney(totalDue, 'USD')} icon={DollarSign}/><Stat label="Advances" value={formatMoney(rows.reduce((sum, row) => sum + ledgerSummary(row.profile.id, row.compensation, monthLedger).advances, 0), 'USD')} icon={DollarSign}/></section><Card><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-2xl font-semibold">Payroll & Dues</h2><p className="mt-1 text-sm text-muted">Advances are included as paid amounts and reduce the outstanding balance.</p></div><div className="flex gap-2"><Field label="Month" type="month" value={payrollMonth} onChange={(e) => setPayrollMonth(e.target.value)}/><Button onClick={() => setShowEntryForm(true)}>+ Add Payroll Entry</Button></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-muted"><tr><th className="pb-3">Employee</th><th>Monthly Salary</th><th>Earnings</th><th>Advances</th><th>Deductions</th><th>Paid</th><th>Outstanding</th><th/></tr></thead><tbody>{rows.map(({ profile, compensation: pay }) => { const summary = ledgerSummary(profile.id, pay, monthLedger); return <tr key={profile.id} className="border-t border-border"><td className="py-3 font-semibold">{profile.full_name}</td><td>{formatMoney(pay?.monthly_salary || 0, 'USD')}</td><td>{formatMoney(summary.earnings, 'USD')}</td><td>{formatMoney(summary.advances, 'USD')}</td><td>{formatMoney(summary.deductions, 'USD')}</td><td>{formatMoney(summary.paid, 'USD')}</td><td className="font-bold text-danger">{formatMoney(summary.due, 'USD')}</td><td><Button type="button" variant="secondary" onClick={() => setLedgerEmployeeId(profile.id)}>View</Button></td></tr>; })}</tbody></table></div></Card></> : null}
    {showEntryForm ? <PayrollEntryModal profiles={team} projects={projects} month={payrollMonth} onClose={() => setShowEntryForm(false)} onSave={async (entry) => { await onAddLedgerEntry(entry); setShowEntryForm(false); }}/>: null}
    {ledgerEmployeeId ? <PayrollLedgerModal profile={team.find((item) => item.id === ledgerEmployeeId)!} compensation={compensation.find((item) => item.employee_id === ledgerEmployeeId)} ledger={monthLedger.filter((entry) => entry.employee_id === ledgerEmployeeId)} onClose={() => setLedgerEmployeeId(null)}/>: null}
  </div>;
}
function Stat({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Users }) { return <Card><Icon className="h-5 w-5 text-gold"/><p className="mt-3 text-2xl font-bold">{value}</p><p className="text-sm text-muted">{label}</p></Card>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-md bg-ivory p-2"><p className="font-bold">{value}</p><p className="text-xs text-muted">{label}</p></div>; }
function PayrollEntryModal({ profiles, projects, month, onClose, onSave }: { profiles: Profile[]; projects: Project[]; month: string; onClose: () => void; onSave: (entry: Omit<EmployeeLedgerEntry, 'id' | 'created_at'>) => Promise<void> }) { const [employeeId, setEmployeeId] = useState(profiles[0]?.id || ''); const [type, setType] = useState<EmployeeLedgerEntry['entry_type']>('Payment'); const [amount, setAmount] = useState(''); const [date, setDate] = useState(`${month}-01`); const [notes, setNotes] = useState(''); const [projectId, setProjectId] = useState(''); const [error, setError] = useState(''); return <Modal title="Add Payroll Entry" onClose={onClose}><form className="space-y-4" onSubmit={async (e) => { e.preventDefault(); if (!employeeId || Number(amount) <= 0) { setError('Choose an employee and enter a valid amount.'); return; } try { await onSave({ employee_id: employeeId, entry_type: type, amount: Number(amount), salary_month: `${month}-01`, payment_method: type === 'Payment' || type === 'Advance' ? 'Bank Transfer' : null, project_id: projectId || null, notes, paid_at: date }); } catch (err) { setError(err instanceof Error ? err.message : 'Entry could not be saved.'); } }}><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Employee" value={employeeId} onChange={(e) => setEmployeeId(e.target.value)}>{profiles.map((p) => <option key={p.id} value={p.id}>{p.full_name}</option>)}</SelectField><SelectField label="Entry Type" value={type} onChange={(e) => setType(e.target.value as EmployeeLedgerEntry['entry_type'])}>{['Salary','Project Payment','Bonus','Advance','Deduction','Payment','Other'].map((x) => <option key={x}>{x}</option>)}</SelectField><Field label="Amount" type="number" min="0.01" step="any" required value={amount} onChange={(e) => setAmount(e.target.value)}/><Field label="Date" type="date" required value={date} onChange={(e) => setDate(e.target.value)}/><SelectField label="Project (optional)" value={projectId} onChange={(e) => setProjectId(e.target.value)}><option value="">No Project</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.project_number} - {p.project_title}</option>)}</SelectField><Field label="Payment Method" value="Bank Transfer" readOnly/></div><TextareaField label="Description / Notes" value={notes} onChange={(e) => setNotes(e.target.value)}/>{error ? <p className="rounded-md bg-red-50 p-3 text-danger">{error}</p> : null}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save Entry</Button></div></form></Modal>; }
function PayrollLedgerModal({ profile, compensation, ledger, onClose }: { profile: Profile; compensation?: EmployeeCompensation; ledger: EmployeeLedgerEntry[]; onClose: () => void }) { const { formatMoney } = useCurrency(); const summary = ledgerSummary(profile.id, compensation, ledger); return <Modal title={`${profile.full_name} — Payroll & Dues`} onClose={onClose} width="max-w-3xl"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Monthly Salary" value={formatMoney(compensation?.monthly_salary || 0, 'USD')}/><Metric label="Project Earnings" value={formatMoney(summary.earnings, 'USD')}/><Metric label="Advances" value={formatMoney(summary.advances, 'USD')}/><Metric label="Deductions" value={formatMoney(summary.deductions, 'USD')}/><Metric label="Paid" value={formatMoney(summary.paid, 'USD')}/><Metric label="Outstanding" value={formatMoney(summary.due, 'USD')}/></div><div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead className="text-muted"><tr><th className="pb-2 text-left">Date</th><th className="text-left">Type</th><th className="text-left">Description</th><th className="text-right">Amount</th></tr></thead><tbody>{ledger.map((item) => <tr key={item.id} className="border-t border-border"><td className="py-2">{item.paid_at}</td><td>{item.entry_type}</td><td>{item.notes || '—'}</td><td className="text-right font-semibold">{formatMoney(item.amount, 'USD')}</td></tr>) || <tr><td colSpan={4} className="py-5 text-center text-muted">No entries for this month.</td></tr>}</tbody></table></div></Modal>; }
function PerformanceTable({ rows }: { rows: Array<{ profile: Profile; metrics: ReturnType<typeof employeeMetrics> }> }) { return <Card><h2 className="font-display text-2xl font-semibold">Employee Performance</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-muted"><tr><th className="pb-3">Employee</th><th>Projects</th><th>Tasks Completed</th><th>Overdue</th><th>Task Rate</th><th>Performance</th></tr></thead><tbody>{rows.map(({ profile, metrics }) => { const taskRate = metrics.employeeTasks.length ? Math.round((metrics.doneTasks.length / metrics.employeeTasks.length) * 100) : 100; return <tr key={profile.id} className="border-t border-border"><td className="py-3 font-semibold">{profile.full_name}</td><td>{metrics.assigned.length}</td><td>{metrics.doneTasks.length} / {metrics.employeeTasks.length}</td><td className="text-danger">{metrics.overdue.length}</td><td>{taskRate}%</td><td><span className="font-bold">{metrics.performance}%</span><div className="mt-1 h-1.5 w-24 rounded bg-ivory"><div className="h-full rounded bg-gold" style={{ width: `${metrics.performance}%` }}/></div></td></tr>; })}</tbody></table></div></Card>; }
